# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end


platform :ios do

	####################################################################################
	lane :update_version do |options|
		# updateVersion(options)
		increment_build_number(xcodeproj: 'LottieAnimationDemo.xcodeproj')
	  end

	  lane :temp_release do
		setup_ci
		# cert
  		# sigh(force: true)
		# match(type: 'appstore')
		build_app
		upload_to_testflight(
			apple_id: "#{DEVELOPER_APP_ID}",
			skip_submission: true,	
			skip_waiting_for_build_processing: true
		)
	  end

	  lane :github do |_options|
		update_version
		
		create_keychain(
		  name: TEMP_KEYCHAIN_USER,
		  password: TEMP_KEYCHAIN_PASSWORD,
		  timeout: 1800,
		  default_keychain: true,
		  unlock: true,
		  lock_when_sleeps: false
		)


		import_certificate(
		#   certificate_path: 'distribution.p12',
		#   certificate_password: 'XXXXXXXXXXX',
		#   certificate_path: '../cert/CertificatesDIST.p12',
		  certificate_path: File.absolute_path("CertificatesDIST.p12"),
		  certificate_password: '123456',
		  keychain_name: TEMP_KEYCHAIN_USER,
		  keychain_password: TEMP_KEYCHAIN_PASSWORD
		)
		
		# install_provisioning_profile(path: "Dist_PushTest.mobileprovision")
		install_provisioning_profile(path: File.absolute_path("Dist_PushTest.mobileprovision"))
		
		
		update_project_provisioning(
		  xcodeproj: 'LottieAnimationDemo.xcodeproj',
		  target_filter: 'LottieAnimationDemo',
		#   profile: 'Dist_PushTest.mobileprovision',
		  profile: File.absolute_path("Dist_PushTest.mobileprovision"),
		  build_configuration: 'Release'
		)

		api_key = app_store_connect_api_key(
		  key_id: APPLE_KEY_ID,
		  issuer_id: APPLE_ISSUER_ID,
		#   key_filepath: '../cert/AuthKey_NWAL8D5A93.p8'
		  key_filepath: File.absolute_path("AuthKey_NWAL8D5A93.p8")
		)
		# disable_automatic_code_signing(path: "LottieAnimationDemo.xcodeproj")
		build_app(workspace: 'LottieAnimationDemo.xcworkspace', scheme: 'LottieAnimationDemo')

		# enable_automatic_code_signing(path: "LottieAnimationDemo.xcodeproj")
		upload_to_testflight(
			skip_submission: true,
			skip_waiting_for_build_processing: true
		)

		# upload_to_app_store(
		#   force: true,
		#   reject_if_possible: true,
		#   skip_metadata: false,
		#   skip_screenshots: true,
		#   languages: ['en'],
		#   release_notes: {
		# 	'default' => 'bug fixed',
		# 	'ko' => 'bug fixed'
		#   },
		#   submit_for_review: true,
		#   precheck_include_in_app_purchases: false,
		#   automatic_release: true,
		#   submission_information: {
		# 	add_id_info_uses_idfa: true,
		# 	add_id_info_serves_ads: true,
		# 	add_id_info_tracks_install: true,
		# 	add_id_info_tracks_action: false,
		# 	add_id_info_limits_tracking: true,
		# 	export_compliance_encryption_updated: false
		#   },
		#   api_key: api_key
		# )
	end
	####################################################################################


	lane :closed_beta do
		keychain_name = TEMP_KEYCHAIN_USER
		keychain_password = TEMP_KEYCHAIN_PASSWORD
		ensure_temp_keychain(keychain_name, keychain_password)
	
		api_key = app_store_connect_api_key(
		  key_id: APPLE_KEY_ID,
		  issuer_id: APPLE_ISSUER_ID,
		  key_content: APPLE_KEY_CONTENT,            
		  duration: 1200,            
		  in_house: false
		)
		
		increment_build_number(xcodeproj: "LottieAnimationDemo.xcodeproj")
		
		cocoapods(
		  clean_install: true,
		  podfile: "../../ios"
		)
	
		match(
		  type: 'appstore',
		  app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
		  git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
		  readonly: true,
		  keychain_name: keychain_name,
		  keychain_password: keychain_password,
		  api_key: api_key
		)
	
		gym(
		  configuration: "Release",
		  workspace: "LottieAnimationDemo.xcworkspace",
		  scheme: "LottieAnimationDemo",
		  export_method: "app-store",
		  export_options: {
			provisioningProfiles: { 
				DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
			}
		  }
		)
	
		pilot(
		  apple_id: "#{DEVELOPER_APP_ID}",
		  app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
		  skip_waiting_for_build_processing: true,
		  skip_submission: true,
		  distribute_external: false,
		  notify_external_testers: false,
		  ipa: "./LottieAnimationDemo.ipa"
		)
	
		delete_temp_keychain(keychain_name)
	  end
end
