# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Android - Build, Test and Deploy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Setup and build
    runs-on: ubuntu-latest
    
    steps:
    # 1
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # 2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    
    # 3
    - name: Cache Ruby - Bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
          
    # 4
    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/
        key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}
    
    # 5
    - name: Cache Gradle Wrapper
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper/
        key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}
    
    # 6
    - name: Grant Permission to Execute
      run: chmod +x ./gradlew
      # run: chmod 777 gradlew
    
    # 7
    - name: Install bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        
    # 8
    - name: Configure Keystore
      run: |
        echo "$SERVICE_ACCOUNT_JSON" > keystore.jks.b64
        base64 -d -i keystore.jks.b64 > app/keystore.jks
        echo "storeFile=keystore.jks" >> keystore.properties
        echo "keyAlias=$ALIAS" >> keystore.properties
        echo "storePassword=$KEY_STORE_PASSWORD" >> keystore.properties
        echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
      env:
        ANDROID_KEYSTORE_FILE: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

    # 9
    - name: Create Firebase Service Credentials file
      run: |
        echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
        base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

    # 10
    - name: Distribute app with 🔥 App Distribution 🚀
      run: bundle exec fastlane distribute
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  
