# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iOS - Build, Test and Deploy iPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repo        
        #uses: actions/checkout@v2
      - run: echo " iOS YML Executes "
      #- run: echo " Print a single environment variable (the commit SHA ) - ${{ github.sha }} "
      - run: echo "Print all environment variables"
      - run:  env
