# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iOS - Build, Test and Deploy iPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      #- name: Check out the directory
      #  uses: actions/checkout@v2
      #  #run: echo " Print a single environment variable (the commit SHA ) - ${{ github.sha }} "
      #- run: echo "Print all environment variables - $ {{env}} "
      #- run: env
      
      # 1
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      # 2
      - name: Login Github User
        run: echo -e "machine github.com\n  login $PERSONAL_ACCESS_TOKEN" >> ~/.netrc
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      # 3
      - name: Install packages
        run: |
          yarn install
          
      # 4
      - name: Bundle and Upload to Testflight - AppStore
        run: |
          cd ios && pod install
          fastlane ios testflight_release_to_app_store
        env:
          FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          #MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
