# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iOS - Build, Test and Deploy iPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      #- name: Check out the directory
      #  uses: actions/checkout@v2
      #  #run: echo " Print a single environment variable (the commit SHA ) - ${{ github.sha }} "
      #- run: echo "Print all environment variables - $ {{env}} "
      #- run: env
      
      # 1
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8 # Used this version in local
          bundler-cache: true
          
      - name: Install Fastlane
        run: cd ios && bundle install

      # 4
      - name: Install packages
        run: npm install
          
      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: 'ios'
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          DEVELOPER_APP_ID: '${{ secrets.APPLE_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_USERNAME }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APP_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.DIST_CERT_P12_PASSWORD }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.MOBILEPROVISION_BASE64 }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          APPLE_KEY_ID: '${{ secrets.APPCONNECT_API_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPCONNECT_API_ISSUER }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPCONNECT_API_KEY_PRIVATE }}'
